"""Meaningful explored territory reconstruction and 360 data structures.

Implements replan §7 and §11 for 360 mode:
- ExploredTerritoryEntry, PriorSummary, ExploreGenerationResult
- Deterministic build_prior_territory(session) from PassRecords only
- No trace scraping, no prose-reason classification.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from .models import (
    Diagnosis,
    PerspectiveCandidate,
    PerspectiveSession,
    SemanticCore,
)


# ─────────────────────────────────────────────────────────────────────────────
# 360 Data structures (§7, §11)
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class ExploredTerritoryEntry:
    """A single record of meaningful explored territory derived from a pass."""

    semantic_core: SemanticCore
    source_kind: Literal[
        "survivor",
        "meaningful_merge",
        "strong_redundant_drop",
        "borderline",
    ]
    source_id: str
    source_pass_id: str
    disposition: str
    reason: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "semantic_core": self.semantic_core.to_dict(),
            "source_kind": self.source_kind,
            "source_id": self.source_id,
            "source_pass_id": self.source_pass_id,
            "disposition": self.disposition,
            "reason": self.reason,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ExploredTerritoryEntry:
        source_kind = data.get("source_kind")
        if source_kind not in (
            "survivor",
            "meaningful_merge",
            "strong_redundant_drop",
            "borderline",
        ):
            raise ValueError(f"Invalid source_kind: {source_kind}")
        return cls(
            semantic_core=SemanticCore.from_dict(data["semantic_core"]),
            source_kind=source_kind,
            source_id=data["source_id"],
            source_pass_id=data["source_pass_id"],
            disposition=data["disposition"],
            reason=data["reason"],
        )


@dataclass
class PriorSummary:
    """Summary of prior explored structures and residual gap hypotheses generated by Call A."""

    dominant_mechanisms: list[str]
    dominant_boundaries: list[str]
    dominant_agency_models: list[str]
    dominant_timescales: list[str]
    shared_assumptions: list[str]
    residual_gap_hypotheses: list[str]

    def to_dict(self) -> dict[str, Any]:
        return {
            "dominant_mechanisms": self.dominant_mechanisms,
            "dominant_boundaries": self.dominant_boundaries,
            "dominant_agency_models": self.dominant_agency_models,
            "dominant_timescales": self.dominant_timescales,
            "shared_assumptions": self.shared_assumptions,
            "residual_gap_hypotheses": self.residual_gap_hypotheses,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PriorSummary:
        return cls(
            dominant_mechanisms=data.get("dominant_mechanisms", []),
            dominant_boundaries=data.get("dominant_boundaries", []),
            dominant_agency_models=data.get("dominant_agency_models", []),
            dominant_timescales=data.get("dominant_timescales", []),
            shared_assumptions=data.get("shared_assumptions", []),
            residual_gap_hypotheses=data.get("residual_gap_hypotheses", []),
        )


@dataclass
class ExploreGenerationResult:
    """Structured result of Call A (Diagnosis, optional PriorSummary, candidates)."""

    diagnosis: Diagnosis
    prior_summary: PriorSummary | None
    candidates: list[PerspectiveCandidate]

    def to_dict(self) -> dict[str, Any]:
        return {
            "diagnosis": self.diagnosis.to_dict(),
            "prior_summary": self.prior_summary.to_dict() if self.prior_summary else None,
            "candidates": [c.to_dict() for c in self.candidates],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ExploreGenerationResult:
        prior_summary_data = data.get("prior_summary")
        prior_summary = PriorSummary.from_dict(prior_summary_data) if prior_summary_data else None
        return cls(
            diagnosis=Diagnosis.from_dict(data["diagnosis"]),
            prior_summary=prior_summary,
            candidates=[PerspectiveCandidate.from_dict(c) for c in data.get("candidates", [])],
        )


# ─────────────────────────────────────────────────────────────────────────────
# Territory reconstruction (§7)
# ─────────────────────────────────────────────────────────────────────────────


def build_prior_territory(session: PerspectiveSession) -> list[ExploredTerritoryEntry]:
    """Deterministically reconstruct meaningful explored territory from PassRecords.

    Implements replan §7 and execution contract:
    - Derives only from structured selections, never from trace scraping or reason prose.
    - Eligible:
      1. survivor: KEEP (admissible, no constraint failures)
      2. meaningful_merge: MERGE + admissible + no constraint failures + strong/borderline + valid target
      3. borderline: BORDERLINE + admissible + no constraint failures + strong/borderline
      4. strong_redundant_drop: DROP + admissible + no constraint failures + strong + marginal low/none
    - Non-eligible (do NOT block territory):
      - hard-constraint failures
      - inadmissible candidates
      - weak standalone quality
      - invalid merge targets
    """
    entries: list[ExploredTerritoryEntry] = []
    if not session or not session.passes:
        return entries

    for pass_record in session.passes:
        candidate_map = {c.candidate_id: c for c in pass_record.candidates}

        # Map KEEP candidates to their assigned P-IDs in candidate generation order
        keep_p_id_map: dict[str, str] = {}
        keep_count = 0
        for cand in pass_record.candidates:
            sel_match = next(
                (s for s in pass_record.selections if s.candidate_id == cand.candidate_id),
                None,
            )
            if sel_match and sel_match.disposition == "KEEP":
                if keep_count < len(pass_record.kept_p_ids):
                    keep_p_id_map[cand.candidate_id] = pass_record.kept_p_ids[keep_count]
                    keep_count += 1

        for sel in pass_record.selections:
            candidate = candidate_map.get(sel.candidate_id)
            if candidate is None:
                continue

            # Hard constraint failures or inadmissibility disqualified immediately
            if not sel.admissible or bool(sel.constraint_failures):
                continue

            disposition = sel.disposition

            if disposition == "KEEP":
                p_id = keep_p_id_map.get(candidate.candidate_id, candidate.candidate_id)
                entries.append(
                    ExploredTerritoryEntry(
                        semantic_core=candidate.semantic_core,
                        source_kind="survivor",
                        source_id=p_id,
                        source_pass_id=pass_record.pass_id,
                        disposition="KEEP",
                        reason=sel.reason,
                    )
                )

            elif disposition == "MERGE":
                # MERGE + admissible + no failures + strong/borderline + valid target
                if (
                    sel.standalone_quality in ("strong", "borderline")
                    and sel.merge_target is not None
                    and sel.merge_target.target_id
                ):
                    target_valid = False
                    if sel.merge_target.kind == "candidate":
                        target_valid = (
                            sel.merge_target.target_id != candidate.candidate_id
                            and sel.merge_target.target_id in candidate_map
                        )
                    elif sel.merge_target.kind == "perspective":
                        perspectives = session.perspectives if session and session.perspectives else {}
                        target_valid = sel.merge_target.target_id in perspectives

                    if target_valid:
                        entries.append(
                            ExploredTerritoryEntry(
                                semantic_core=candidate.semantic_core,
                                source_kind="meaningful_merge",
                                source_id=candidate.candidate_id,
                                source_pass_id=pass_record.pass_id,
                                disposition="MERGE",
                                reason=sel.reason,
                            )
                        )
            elif disposition == "BORDERLINE":
                # BORDERLINE + admissible + no failures + strong/borderline
                if sel.standalone_quality in ("strong", "borderline"):
                    entries.append(
                        ExploredTerritoryEntry(
                            semantic_core=candidate.semantic_core,
                            source_kind="borderline",
                            source_id=candidate.candidate_id,
                            source_pass_id=pass_record.pass_id,
                            disposition="BORDERLINE",
                            reason=sel.reason,
                        )
                    )

            elif disposition == "DROP":
                # DROP + admissible + no failures + strong + marginal low/none
                if (
                    sel.standalone_quality == "strong"
                    and sel.marginal_contribution in ("low", "none")
                ):
                    entries.append(
                        ExploredTerritoryEntry(
                            semantic_core=candidate.semantic_core,
                            source_kind="strong_redundant_drop",
                            source_id=candidate.candidate_id,
                            source_pass_id=pass_record.pass_id,
                            disposition="DROP",
                            reason=sel.reason,
                        )
                    )

    return entries


# ─────────────────────────────────────────────────────────────────────────────
# Prompt rendering helpers for 360 (§11)
# ─────────────────────────────────────────────────────────────────────────────


def render_explored_territory(entries: list[ExploredTerritoryEntry]) -> str:
    """Render meaningful explored territory entries for prompt inclusion."""
    if not entries:
        return "(none — no prior meaningful territory recorded)"

    parts = []
    for entry in entries:
        core = entry.semantic_core
        kind_label = entry.source_kind.upper()
        parts.append(
            f"### [{kind_label}] {entry.source_id} (Pass {entry.source_pass_id})\n"
            f"- Central problem: {core.central_problem}\n"
            f"- Mechanism: {core.mechanism}\n"
            f"- Load-bearing claim: {core.load_bearing_claim}\n"
            f"- System boundary: {core.system_boundary or 'Not specified'}\n"
            f"- Agency model: {core.agency_model or 'Not specified'}\n"
            f"- Unit of analysis: {core.unit_of_analysis or 'Not specified'}\n"
            f"- Temporal logic: {core.temporal_logic or 'Not specified'}\n"
            f"- Prior disposition: {entry.disposition}"
        )
    return "\n\n".join(parts)


def render_prior_summary(summary: PriorSummary | None) -> str:
    """Render prior summary for Call B prompt inclusion."""
    if not summary:
        return "(none)"

    lines = [
        f"- Dominant mechanisms: {', '.join(summary.dominant_mechanisms) if summary.dominant_mechanisms else '(none)'}",
        f"- Dominant boundaries: {', '.join(summary.dominant_boundaries) if summary.dominant_boundaries else '(none)'}",
        f"- Dominant agency models: {', '.join(summary.dominant_agency_models) if summary.dominant_agency_models else '(none)'}",
        f"- Dominant timescales: {', '.join(summary.dominant_timescales) if summary.dominant_timescales else '(none)'}",
        f"- Shared assumptions: {', '.join(summary.shared_assumptions) if summary.shared_assumptions else '(none)'}",
        f"- Residual gap hypotheses: {', '.join(summary.residual_gap_hypotheses) if summary.residual_gap_hypotheses else '(none)'}",
    ]
    return "\n".join(lines)
